stages:
  - test

simple_test_job:
  stage: test
  script:
    - echo "Olá, Runner! O job foi executado com sucesso."
    - echo "O sistema operacional é:"
    - uname -a
    - echo "Teste concluído."